### ISSUE TITLE
Sequence Diagram Page Formation

### ISSUE THREAD

**Issue by effervescent-shot** [bounswe/bounswe2017group11#109]

**Comment by effervescent-shot** [comment]
Please comment which sequence diagrams are correct and current. Erroneous ones will be removed.

**Comment by akoksal** [comment]
1,3 and 4 are correct and 2 is incorrect.

**Comment by anilseyrek** [comment]
12 and 13 are correct. 14 is unnecessary and incorrect.

**Comment by effervescent-shot** [comment]
Sequence Diagram page was updated.

Sequence diagrams belonging use case 2,5,6,7 and 14 were removed. They were erroneous and it has been thought that 10 sequence diagrams are enough for exhibition.
