### ISSUE TITLE
Create API documentation project with Swagger - Enes

### ISSUE THREAD

**Issue by enescakir** [bounswe/bounswe2017group11#137]

**Comment by enescakir** [comment]
Starter project is created at Swagger: https://swaggerhub.com/apis/enescakir/culturage/1.0.0
Don't forget to choose UI mode. 
![swagger](https://user-images.githubusercontent.com/993199/31514675-15c689ca-af9b-11e7-8684-165bef19a180.png)

**Comment by rizaozcelik** [comment]
We are looking forward to that! 😳 👊
