### ISSUE TITLE
review first 3 udacity android lessons then study 4th lesson - giray

### ISSUE THREAD

**Issue by GirayEryilmaz** [bounswe/bounswe2017group11#139]
Review first 3 Udacity android courses:
 - Android Basics: User Interface 
 - Android Basics: User Input
 - Android Basics: Multiple App Screens

Then study 4th course
 - Android Basics: Networking

**Comment by akoksal** [comment]
Keep up the good work!
https://www.youtube.com/watch?v=KMU0tzLwhbE
