### ISSUE TITLE
Connect android and backend - android

### ISSUE THREAD

**Issue by rizaozcelik** [bounswe/bounswe2017group11#143]
Establish API connection from the android app and replace placeholder data in the app with the data from the API.

Deadline: 23/10/2017, 23:55

**Comment by ozmenbrn** [comment]
Profile page is connected with api, Yet there is a bug with the image. The users' without profile page cannot connect yet.

**Comment by rizaozcelik** [comment]
Signup, login, news feed and item pages are up and running. Upload and profile page is on their way!

**Comment by ozmenbrn** [comment]
The image bug has been solved. 
Saving changes on profile page will be implemented soon.

**Comment by rizaozcelik** [comment]
Upload page is also up!

**Comment by ozmenbrn** [comment]
Profile Page is completed! The code must be refactored again, there is a bug about memory while trying to upload 4+ image.
