### ISSUE TITLE
Fetch latest changes and run test page

### ISSUE THREAD

**Issue by kuzdogan** [bounswe/bounswe2017group11#145]
The frontend team, please pull the updated frontend branch. Install npm libraries and run the test page by `npm start`

**Comment by kuzdogan** [comment]
All good, running

**Comment by hilalbenzer** [comment]
Displayed Hello World!

**Comment by halilkalkan** [comment]
Done!

**Comment by ptpam** [comment]
The required files were installed and the test page was seen.
