### ISSUE TITLE
LDP Requirements - Ezgi 

### ISSUE THREAD

**Issue by effervescent-shot** [bounswe/bounswe2017group11#15]
- [ ] Web

 annotation protocol based on LDP is going to be used in our project. It may or may not have its special requirements that need to be considered. A research should be done on LDP and requirements should be identified. 

Due 28.02.2018 23:59

**Comment by anilseyrek** [comment]
I did a small research on the web that might help you. Here is what I found:

[https://www.w3.org/DesignIssues/LinkedData.html](https://www.w3.org/DesignIssues/LinkedData.html)
This is an article written by Tim Berners-Lee. It is one of the first writings about linked data.

Here are examples and LDP implementations:
[https://www.w3.org/2012/ldp/wiki/Examples](https://www.w3.org/2012/ldp/wiki/Examples)
[https://www.w3.org/wiki/LDP_Implementations](https://www.w3.org/wiki/LDP_Implementations)
I did not delve deeper into the links above but I found some resources:

[http://marmotta.apache.org/](http://marmotta.apache.org/)
"Apache Marmotta is an Open Platform for Linked Data."
[http://fedora-commons.org/](http://fedora-commons.org/)
"open source repository system for the management and dissemination of digital content"

And after all, I think we will use REST APIs or build one of them; so this tutorial site would be very helpful:
[http://www.restapitutorial.com](http://www.restapitutorial.com)
