### ISSUE TITLE
Write Milestone 1 Report - Deadline (27.10.2017 - 5pm)

### ISSUE THREAD

**Issue by enescakir** [bounswe/bounswe2017group11#157]

**Comment by rizaozcelik** [comment]
I think we should devote one person from each them to this job. Though it looks like it would not be too complex, it would be easier for three people than one.

**Comment by effervescent-shot** [comment]
I am going to help

**Comment by ozmenbrn** [comment]
Excel sheet is opened and shared on google drive.

**Comment by akoksal** [comment]
Backend part is done!

**Comment by ptpam** [comment]
Frontend part is also done.

**Comment by ozmenbrn** [comment]
Android part is also done, all 3 parts are merged into 1 pdf report and uploaded to wiki.
