### ISSUE TITLE
user may use invalid search queries

### ISSUE THREAD

**Issue by GirayEryilmaz** [bounswe/bounswe2017group11#190]
users search query may contain characters that are invalid  in urls, this goes for tags too because they are used for tag search.

**Comment by enescakir** [comment]
You can use [URLEncoder](https://stackoverflow.com/questions/10786042/java-url-encoding-of-query-string-parameters) bro ☺️

**Comment by GirayEryilmaz** [comment]
thanks for the suitable solution dude, easier than i thought
