### ISSUE TITLE
Move Swagger documentation to Postman documentation - Enes

### ISSUE THREAD

**Issue by enescakir** [bounswe/bounswe2017group11#192]
I learned Postman is creating documentation for endpoints automatically. It's amazing. I don't bother with Swagger.

**Comment by enescakir** [comment]
Postman documentation is create at [here](https://documenter.getpostman.com/view/2986669/culturage-api/71FWB4x)

**Comment by enescakir** [comment]
Documentation link in README is updated

**Comment by effervescent-shot** [comment]
God bless your hands!
