### ISSUE TITLE
Fix N+1 query problem for database relations - Enes

### ISSUE THREAD

**Issue by enescakir** [bounswe/bounswe2017group11#193]

**Comment by enescakir** [comment]
N+1 query problem is very famous in app development world. 
For example, we have 100 `Item`s and each item has `Comment`s.
We want to list the all `Item`s with their comments. 
Simply, we can list `Item`s with `SELECT * FROM items` query. 
But for getting comments, we should execute `SELECT * FROM comments WHERE item_id = ?` for each `Item`. It makes 101 SQL query and it's very big performance issue.
We can solve this issue with eager loading.

**Comment by enescakir** [comment]
Write setup_eager_loading method for ItemSerializer

**Comment by effervescent-shot** [comment]
God bless your hands!
