### ISSUE TITLE
API research - how deep, detailed

### ISSUE THREAD

**Issue by GirayEryilmaz** [bounswe/bounswe2017group11#2]
Should we learn how to use one api or our purpose is to learn the general "api idea" and some details so that in the future we can code our own for the project.

**Comment by effervescent-shot** [comment]
I supposed purpose is learning the general 'api idea' rather than learning
how to use it. We may use this idea later when we are coding our project.

N. Ezgi YÜCETÜRK
Gsm: +90 531 249 2367
Email: nhlezgiyctrk@gmail.co <nhlezgiyctrk@gmail.com>m
           ezgi.yuceturk@estiem.org
