### ISSUE TITLE
Write endpoints for uploading multiple files to Item - Enes

### ISSUE THREAD

**Issue by enescakir** [bounswe/bounswe2017group11#200]

**Comment by enescakir** [comment]
`/api/items/{ITEM_ID}/medias` endpoint is added for uploading additional medias to Item

**Comment by enescakir** [comment]
Supported file formats:
`Image` => `jpg, jpeg, png, gif`
`Video` => `mp4, mov, avi, 3gp, mkv`
`Audio` => `mp3, aav`
`Document` =>  `pdf, txt`

**Comment by effervescent-shot** [comment]
God bless your hands!
