### ISSUE TITLE
Enter 10 items

### ISSUE THREAD

**Issue by kuzdogan** [bounswe/bounswe2017group11#242]
Everyone please add 10 heritage items so that we will achive the final task of adding >100 items

**Comment by kuzdogan** [comment]
Or can anyone with database access could inform us how many items more we need? @EnesCakir ?

**Comment by ptpam** [comment]
10 items are uploaded!!

**Comment by hilalbenzer** [comment]
Done my part. Current item count seems to be 92

**Comment by rizaozcelik** [comment]
I am done as well.

**Comment by kuzdogan** [comment]
Completed

**Comment by halilkalkan** [comment]
I'm done

**Comment by effervescent-shot** [comment]
Done

**Comment by kuzdogan** [comment]
We seem to have enough items, closing the issue
