### ISSUE TITLE
the Requirements Page Update - Requirements Team (Hilal, Giray, Enes, Abdüllatif)

### ISSUE THREAD

**Issue by GirayEryilmaz** [bounswe/bounswe2017group11#28]
Please update the requirements wiki page according to [the To-Do part of the third meeting](https://github.com/bounswe/bounswe2017group11/wiki/Meeting---3#to-do) 
Until 26.02.2017 23.59

**Comment by GirayEryilmaz** [comment]
4., 5., 6. and 7. matters are done (hopefully as desired, take a look)
1., 2., 3., 8., 9. are left

**Comment by GirayEryilmaz** [comment]
some ideas on advanced search:
name, exact words, region, in title, in text, author, tags, period, meta data - video, photo, audio
regex?????

**Comment by akoksal** [comment]
2. and 8. is done. Please take a look.

**Comment by akoksal** [comment]
1. is done, too. Please take a look and edit parts you don't like. I think 1. should be integrated with mockup group too because they are designing the home page too.

**Comment by hilalbenzer** [comment]
Moved search requirements and homepage requirements under user requirements. Take a look and feel free to edit
