### ISSUE TITLE
Conduct a search on Mockup - Anıl, Barın, Halil, Rıza, Fatih

### ISSUE THREAD

**Issue by rizaozcelik** [bounswe/bounswe2017group11#29]
* Learn what the mockup is and how it should be done.
* Take a look at mockups of last years' group if necessary.
* Search the possible tools that might be useful.
* Think about possible designs for both the web and Android applications

Deadline: 26/02/2017, 23.59

**Comment by rizaozcelik** [comment]
Some mockup tools that can be used:
* https://www.fluidui.com/
* https://proto.io/en/signup/
* https://www.invisionapp.com/tour/android-prototyping
* www.ninjamock.com

**Comment by rizaozcelik** [comment]
www.ninjamock.com is selected as mockup tool

**Comment by ozmenbrn** [comment]
done with the learning mockup and started to design on www.ninjamock.com
