### ISSUE TITLE
Create mockups - Anıl, Barın, Fatih, Halil, Rıza

### ISSUE THREAD

**Issue by rizaozcelik** [bounswe/bounswe2017group11#30]
Everyone should create two mockups each. Anıl, Barın and Halil will be responsible for web mockup and Rıza and Fatih will be responsible for Android design. 

Note that everyone should take a look at each other's design and should comment if necessary.

Deadline: 27/02/2016 23:59

**Comment by ozmenbrn** [comment]
Started to design for web:
     - registration/login page
     - profile management page

**Comment by anilseyrek** [comment]
Started to design for web:
- home page
- heritage page

**Comment by rizaozcelik** [comment]
Completed the design of
* Upload page
* Cultural heritage item page
for Android app

**Comment by halilkalkan** [comment]
Started to design for web:

- Upload page

**Comment by anilseyrek** [comment]
Completed the design of
- home page
- heritage page

**Comment by ozmenbrn** [comment]
Completed the design of

  -   registration/login page
  -   profile management page

**Comment by halilkalkan** [comment]
Completed the design of: 

- Upload page

**Comment by anilseyrek** [comment]
Done
