### ISSUE TITLE
Form 'registered user' and 'comment' classes - Giray

### ISSUE THREAD

**Issue by GirayEryilmaz** [bounswe/bounswe2017group11#48]
Form 'registered user' and 'comment' classes with fields and methods until 12.03.2017 23.59

**Comment by GirayEryilmaz** [comment]
still there is work to be done but ,i believe, the general view is complete. Feel free to edit or criticize.
it is on the draw.io

**Comment by rizaozcelik** [comment]
I think registered users should also be able to edit, upload, vote, flag posts which a guest user will not be able to. 

So I will add these methods as well.

**Comment by GirayEryilmaz** [comment]
okey, thanks man, i am totally cool with that but, 

Shouldn't these be functions of item class:
+uploadItem(item : Item) : Boolean
+editItem(item : Item) : Boolean;
i mean i wouldn't go like 

`RegisteredUserCrazyCoder.editItem(BlueMosque)`

i would rather do 

`BlueMosque.edit()`

but either way we can make it work though.

others too go with similar ways

Shouldn't this be functions of comment class:
+comment(comment : String) : Boolean  which i forgot to add there;

Shouldn't these be functions of tag class or perhaps item and comment classes respectively:
+addTagToAnItem(tag : Tag, item : Item) : Boolean
+TagAComment(tag : Tag, comment : Comment) : Boolean
 
i am not sure what to do with these:
+vote(vote : Integer) : Boolean
+flag(item : Item) : Boolean

**Comment by rizaozcelik** [comment]
You are right, we can make it work either way. That is a design choice.

The way I have designed looks more natural and structured to me. Because, when I am looking at the functions of user class I can directly see what a user can or cannot do. 

Maybe it is just me thinking this way. You can change them if you wish. I am cool with that as well.
