### ISSUE TITLE
Create Sequence Diagrams

### ISSUE THREAD

**Issue by anilseyrek** [bounswe/bounswe2017group11#52]
Abdullatif Köksal is assigned to do sequence diagrams of Use Cases 1, 2, 3, and 4.
Halil Kalkan is assigned to do sequence diagrams of Use Cases 5, 6, and 7.
Mustafa Enes Çakır is assigned to do sequence diagrams of Use Cases 8, 9, 10, and 11.
Anıl Seyrek is assigned to do sequence diagrams of Use Cases 12, 13, and 14.
Fatih Aşağıdağ is assigned to do sequence diagrams of Use Cases 15, 16, and 17.

Due: 13/03/2017, 23:59

**Comment by anilseyrek** [comment]
Sequence diagrams for the 12th, 13th and 14th use cases were added.

**Comment by enescakir** [comment]
Sequence diagrams #8, 9, 10, 11 added

**Comment by fasagidag** [comment]
Sequence diagrams #15,16 and 17 added
