### ISSUE TITLE
Creating Gantt Chart

### ISSUE THREAD

**Issue by halilkalkan** [bounswe/bounswe2017group11#55]
We will use https://app.smartsheet.com/ to create Gantt Chart.

**Comment by halilkalkan** [comment]
Requirements and Design parts are completed.

**Comment by fasagidag** [comment]
Recommendation System and Feed,Subscription, Last Enhancements, Testing  and Presentation parts are completed

**Comment by GirayEryilmaz** [comment]
added Reviewing project documents, Setting up the project environment, Learning the basics of Web/Android, Database design parts.

**Comment by hilalbenzer** [comment]
Sign up and Login System, Item upload, Commenting and Rating System, Searching System with Semantic Tags parts are done.
